# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Giovanni Cabrera Moreno
title: Senior Backend Developer
email: giovannicabreramoreno@gmail.com
website: https://gioalcamofly.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  gioalcamofly
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: giovannicabreramoreno
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Giovanni and I am a backend developer. I've worked for one of the most innovative companies in Spain as well as one of the main IT consulting companies in the Canary Islands. 
  During my career, I've got experience mainly with backend development (Python, Laravel, Java), but also with frontend development (Vue, Java) as well as IoT. I also have had to face challenges
  like teaching a junior developer who recently passed university. 

  I define myself as a curious person who likes to learn whatever I don't know yet and also as someone who tries to contribute with new ideas and points of view.

  My best skills are: <mark>Quick learning</mark> and <mark>bad jokes</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Open Ximdex Evolution
        link: https://www.ximdex.com/
        link_text: https://www.ximdex.com/
        sub_title: Senior Backend Developer
        caption: September 2021 - now
        description: |
          - Developed APIs using Python (Django and Flask)
          - Developed AWS, Azure and IBM Watson clients using Symfony
          - Used MySQL and Neo4j databases
          - Developed a service aggregator for text semantics systems using Symfony
          - Followed agile development
          - Managed several projects (team, analysis, deployment, research, servers, client meetings...)
          - Teached a junior developer
          - Started TDD and DevOps on a project using Python unittest and Github Actions
          - Used Nginx, Apache and Docker to deploy applications
          - Developed front applications using Jinja2 templates and React
      
      - title: Light Painter
        link: https://www.instagram.com/lightpainterteam/?hl=en
        link_text: https://www.instagram.com/lightpainterteam/?hl=en
        sub_title: Founder
        caption: December 2017 - March 2020
        description: |
          - Created and developed a new technology using IoT
          - Developed a mobile application using Ionic Framework
          - Created electronic circuits
          - Analyzed from business side: business opportunities, competitors, potential benefits and expenses, risks...
          - Managed a team of 4 developers
          - Pitched the project to possible investors
        
      - title: Open Canarias
        link: https://www.opencanarias.com/
        link_text: https://www.opencanarias.com/
        sub_title: Full-Stack Developer
        caption: May 2019 - September 2021
        description: |
          - Developed backend and frontend applications in Vue and Laravel
          - Developed backend and frontend applications in JavaEE
          - Managed databases in Oracle and MySQL
          - Developed Android applications in Java and Kotlin
          - Used DevOps
          - Developed using microservices architecture
          - Used and managed (lightly) Kubernetes containers
          - Followed agile development
          - Followed clean code and TDD conventions

      - title: ASTICAN
        link: https://www.astican.es/
        link_text: https://www.astican.es/
        sub_title: Junior Developer
        caption: September 2018 - May 2019
        description: |
              - Managed Oracle Databases
              - Developed in Oracle PL-SQL
              - Developed scripts to automate processes using Java and PHP
              - Developed web applications using JS and HTML5
      
      - title: Project Mi5
        link: https://github.com/ProjectMi5
        link_text: https://github.com/ProjectMi5
        sub_title: Junior Developer (Internship)
        caption: January 2018 - August 2018
        quote: >
          Innovative education
        description: | # this will include new lines to allow paragraphs
            - Developed mobile and web applications using Ionic Framework
            - Developed IoT applications using Arduino
            - Worked with several kinds of hardware, as sensors, robots and 3d printers
            - Managed innovative projects: proposals, pitchs, suggestions, resource management, analysis, goals, approaches...
            - Used DevOps to improve efficiency

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Light Painter
        link: https://www.instagram.com/lightpainterteam/?hl=en
        link_text: https://www.instagram.com/lightpainterteam/?hl=en
        quote: >
          We believe in your art
        description: | # this will include new lines to allow paragraphs
          I started this project as my final project to pass university. It consisted on a IoT system that allows you to take light painting pictures automatically.
          For that, I had to develop a mobile app and a hardware systems with motors and controllers. Both systems needed to be able to communicate with each other and, besides,
          the hardware one had to be able to shoot the camera wirelessly. It is a really cool system, so if you are interested in knowing don't hesitate to ask me.

          After university, I continued developing it and even entered a pre-accelerator program (Explorer by Banco Santander) where I learnt the insights of a business and the lean startup
          philosophy. Thanks to this program, I could pitch in front of possible investors and I even won a price for the Most Disruptive Technology in my island. 

          Once the program finished, I reunited a little team of developers (software and hardware developers) to continue working on this project. We even went to Berlin to a major light painting event
          to meet some possible clients and gain some feedback.

          Unfortunately, I had to left this aside because I didn't have the needed time to spend.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universidad de Las Palmas de Gran Canaria
        caption: 2014 - 2018
        sub_title: BSc Computer Science

      - title: Universidad Nacional de Educacion a Distancia
        caption: 2018- 2020 (half course)
        sub_title: MsC Investigation in Artifitial Intelligence

  - title: Skills
    layout: list
    content: 
      - layout: left
        title: Programming Languages
        caption: From more proficiency to less
        description: |
          Python, PHP, Java, Javascript, HTML5, C++, Kotlin, CSS

      - title: Frameworks
        caption: From more proficiency to less
        description: |
          Laravel, Flask, Vue, Django, Symfony, Ionic, Spring

      - title: Databases
        caption: From more proficiency to less
        description: |
          MySQL, Oracle, Neo4j

      - title: Agile methodologies
        description: |
          Scrum, TDD, Clean Code, Kanban

      - title: Systems and others
        caption: From more proficiency to less
        description: |
          Git, Linux, Docker, ML, Apache, Nginx

  - title: Strenghs and weaknesses
    layout: list
    content:
      - layout: left
        title: Strenghs
        description: |
          Quick learning, resourceful, team working, innovative, adaptable

      - title: Weaknesses
        description: |
          Sometimes too persistent on problems, shy
      

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Photography
      - Gaming
      - Sports
      - And coffee, of course

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
